// mutations
export const ADD_PRODLISTDATA = 'ADD_PRODLISTDATA'
export const ADD_PRODLISTDATA_ACTION_RESET = 'ADD_PRODLISTDATA_ACTION_RESET'
// actions
export const ADD_PRODLISTDATA_ACTION = 'ADD_PRODLISTDATA_ACTION'
export const ADD_AUTHORLISTDATA_ACTION_RESET = 'ADD_AUTHORLISTDATA_ACTION_RESET'
export const ADD_AUTHORLISTDATA = 'ADD_AUTHORLISTDATA'
// actions

export const ADD_AUTHORLISTDATA_ACTION = 'ADD_AUTHORLISTDATA_ACTION'